name: Install dependencies

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        shell: bash
        run: |
          if [ -f yarn.lock ]; then
            yarn install --immutable  # Yarn 2+ / Modern (not --frozen-lockfile)
          elif [ -f package-lock.json ]; then  
            npm ci
          else
            yarn install  # Fallback
          fi

